dist: trusty
language: python
python:
  - "2.7.14"

matrix:
  include:

    # Job 1: Linters
    - env: python2-linters
      sudo: false
      language: python
      python: "2.7.14"
      script:
        - pip install -r requirements/prod.txt --no-deps --require-hashes
        - pip check
        - pip install -r requirements/dev.txt --no-deps
        - pip install -r requirements/mozautomation.txt --no-deps
        - pip check
        - flake8 --show-source

    # Job 2: Unit Tests in Docker env
    - env: docker-wptsync-test
      # Upgrade to newer docker version
      addons:
        apt:
          packages:
            - docker-ce
      sudo: required
      services:
        - docker
      install:
        - docker build -t wptsync_dev --file docker/Dockerfile.dev .
        - sudo chown -R 10001 .
      script:
        - ./bin/run_docker_dev.sh test --no-flake8

    # Job 3: Static Analysis
    - env: static-analysis
      sudo: false
      language: python
      python: "2.7.14"
      script:
        - pip install bandit
        - bandit -r sync -ll

notifications:
  irc:
    channels:
      - "irc.mozilla.org#wpt-sync"
    on_success: change
    on_failure: always
